apps/patroni/models.py
# -*- coding:utf-8 -*-

from django.db import models

class Patron(models.Model):
    nazwa = models.CharField(u"Nazwa", max_length=255)
    opis = models.TextField(u"Opis", blank = True, null = True)
    url = models.URLField(u"URL")
    banner_small = models.ImageField(u"Mały banner/logo", help_text=u"wyświetlane w blokach, maksymalna szerokość 220px", upload_to="patroni")
    banner = models.ImageField(u"Duży banner", help_text=u"Banner na stronę patronów", upload_to="patroni_bannery")
    kolejnosc = models.IntegerField(u"Kolejność", default=100)
    
    def __unicode__(self):
        return self.nazwa
    
    class Meta:
        verbose_name=u"Patron"
        verbose_name_plural=u"Patroni"
        ordering = ['kolejnosc']

class Sponsor(models.Model):
    nazwa = models.CharField(u"Nazwa", max_length=255)
    url = models.URLField(u"URL")
    banner_small = models.ImageField(u"Mały banner/logo", help_text=u"wyświetlane w blokach, maksymalna szerokość 230px / full ", upload_to="sponsorzy")
    banner = models.ImageField(u"Duży banner", help_text=u"Banner na stronę patronów", upload_to="sponsorzy_bannery")
    kolejnosc = models.IntegerField(u"Kolejność", default=100)
    
    def __unicode__(self):
        return self.nazwa

    class Meta:
        verbose_name = u"Sponsor"
        verbose_name_plural = u"Sponsorzy"
        ordering = ['kolejnosc']

apps/patroni/views.py
# -*- coding:utf-8 -*-

from patroni.models import Sponsor, Patron

from django.views.generic.list import ListView

class PatroniView(ListView):
	template_name = 'patroni/patroni_list.html'
	model = Patron

class SponsorzyView(ListView):
	template_name = 'patroni/patroni_list.html'
	model = Sponsor

arda/templates/patroni/block_patroni.html
<h2>Patroni medialni</h2>
<div class="link-cycle">
	<div class="link-tiles">
	{% for patron in objects_list %}
		<a href="{{ patron.url }}" class="tile"><img src="{{ MEDIA_URL }}{{ patron.banner_small.url }}" alt="{{ patron.nazwa }}"></a>
	<!-- / link-tiles -->
	{% if not forloop.last %}{% if forloop.counter|divisibleby:"6" %}</div><div class="link-titles">{% endif %}{% endif %}
	{% endfor %}
	</div>

arda/templates/patroni/block_sponsorzy.html
<h2>Sponsorzy</h2>
<div class="link-tiles">
	{% for sponsor in objects_list %}
	<a href="{{ sponsor.url }}" class="tile wide"><img src="{{ MEDIA_URL}}{{ sponsor.banner_small.url }}" alt="{{ sponsor.nazwa }}"></a>
	{% endfor %}
</div>
<!-- / link-tiles -->

arda/templates/patroni/patroni_list.html
{% extends 'base.html' %}

{% block title %}Partnerzy{% endblock %}

{% block main %}
<div class="col-inner">
    {% if sponsor_list %}
    <h1>Sponsorzy</h1>
    <div class="link-tiles">
    {% for object in sponsor_list %}
        <a class="tile" href="{{ object.url }}" title="{{ object.nazwa }}"><img class="bcenter" src="{{ object.banner.url }}" alt="{{ object.nazwa }}"/></a>
    {% endfor %}
    </div>
    {% endif %}
    {% if patron_list %}
    <h1>Patroni medialni</h1>
    <div class="link-tiles full-width">
    {% for object in patron_list %}
        <a class="tile" href="{{ object.url }}" title="{{ object.nazwa }}"><img class="bcenter" src="{{ object.banner.url }}" alt="{{ object.nazwa }}"/></a>
    {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}