apps/zapisy/models.py
# -*- coding: utf-8 -*-
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User, UserManager

# Create your models here.

class Plemie(models.Model):
    nazwa = models.CharField("Nazwa plemienia",max_length=255)
    showonpage = models.BooleanField('Pokaż na stronie',default=False)
    can_register = models.BooleanField(u"Można się zapisać", default=True)
    rekruter_mail = models.CharField("Email rekrutującej osoby",max_length=255)
    nick = models.CharField("Nick rekrutera",max_length=255)
    gg = models.CharField("GG rekrutera",max_length=255,blank=True)
    opis = models.TextField('Opis plemienia',blank=True)

    class Meta:
        verbose_name = u"Plemię"
        verbose_name_plural = 'Plemiona'
        ordering = ['nazwa']

    def __unicode__(self):
        return self.nazwa

class Zlot(models.Model):
    rok = models.IntegerField("Rok zlotu",unique=True)
    start = models.DateField("Początek Zlotu")
    koniec = models.DateField("Koniec Zlotu")
    zapisy_otwarte = models.BooleanField(u"Czy zapisy są otwarte",default=False)
    miejsce = models.CharField(u"Miejsce zlotu",max_length=255,blank=True,null=True)

    class Meta:
        verbose_name="Zlot"
        verbose_name_plural="Zloty"

    def __unicode__(self):
        return "Zlot Arda "+str(self.rok)

class Larp(models.Model):
    zlot = models.ForeignKey(Zlot)
    nazwa = models.CharField(u"Nazwa", max_length = 255)
    slug = models.SlugField(u'Slug')
    opis = models.TextField(u"Opis")
    zapisy_otwarte = models.BooleanField(u"Czy zapisy są otwarte", default = False)
    obraz = models.ImageField(u"Obraz pod fb", upload_to = 'larpy', blank = True)

    class Meta:
        verbose_name = u"Larp"
        verbose_name_plural = u"Larpy"

    def __unicode__(self):
        return self.nazwa

class Frakcja(models.Model):
    larp = models.ForeignKey(Larp)
    nazwa = models.CharField(u"Nazwa", max_length = 255)
    slug = models.SlugField(u"Slug")
    opis = models.TextField(u"Opis")
    wprowadzenie = models.TextField(u"Wprowadzenie", blank = True, null = True)
    zasady_rekrutacji = models.TextField(u"Zasady przyjmowania", blank = True, null = True)
    mozna_wybrac = models.BooleanField(u'Czy można wybrać w zapisie?', default = True)
    dostepny_opis = models.BooleanField(u"Czy można zobaczyć opis?", default = True)
    dostepna_rekrutacja = models.BooleanField(u"Czy można zobaczyć reguły rekrutacji?", default = True)
    limit = models.IntegerField(u'Limit miejsc', help_text=u"Limit miejsc we frakcji bez zarezerwowanych miejsc", blank = True, null = True)
    minimum = models.IntegerField(u'Minimum osób', help_text=u"Minimalna ilość osób, aby frakcja mogła w ogóle zaistnieć w grze", blank = True, null = True)
    rezerwowane = models.IntegerField(u"Zarezerwowane miejsca", help_text=u"Miejsca zarezerwowane dla zgłoszonych postaci", blank = True, null = True)
    image = models.ImageField("Obraz", upload_to='frakcje', blank=True)

    class Meta:
        verbose_name = u'Frakcja'
        verbose_name_plural = u'Frakcje'
        ordering = ['nazwa']

    def __unicode__(self):
        return self.nazwa

    def wolne_miejsca(self):
        if self.limit:
            return self.limit-self.frakcjauczestnik_set.filter(rezerwowany=False).count()
        return 0;

    def zajete_miejsca(self):
        if self.frakcjauczestnik_set:
            return self.frakcjauczestnik_set.count()
        return 0


class Uczestnik(User):
    email_sent = models.BooleanField("Wyslane powiadomienie", default = False) # powiadomienie o zmianie hasła

    objects = UserManager()

    def get_register_hash(self):
        import hashlib
        return hashlib.sha1('magicznykluczgandalfa' + self.username.encode('utf-8') + self.email).hexdigest()

    class Meta:
        verbose_name = 'Uczestnik'
        verbose_name_plural = 'Uczestnicy'
        ordering = ['username']

    def __unicode__(self):
           return u"%s" % self.username


class Uczestnictwo(models.Model):
    zlot = models.ForeignKey(Zlot)
    uczestnik = models.ForeignKey(Uczestnik)
    zaplacil = models.BooleanField(u"Zapłacił za zlot",default=False)
    caly = models.BooleanField(u"Czy na cały zlot",default=True)
    od = models.DateField("Od",help_text=u"Jeżeli jedziesz na część zlotu, podaj od kiedy będziesz (RRRR-MM-DD)<br/>W przeciwnym razie pozostaw puste.",blank=True,null=True)
    do = models.DateField("Do",help_text=u"Jeżeli jedziesz na część zlotu, podaj do kiedy będziesz (RRRR-MM-DD)<br/>W przeciwnym razie pozostaw puste.",blank=True,null=True)
    timestamp = models.DateTimeField("Dodano", auto_now_add=True, default="2012-05-01")

    class Meta:
        verbose_name="Uczestnictwo"
        verbose_name_plural="Uczestnictwa"

    def __unicode__(self):
        return unicode(self.uczestnik)+" @ "+unicode(self.zlot)

    def email(self):
        return self.uczestnik.email

class FrakcjaUczestnik(models.Model):
    frakcja = models.ForeignKey(Frakcja)
    uczestnik = models.ForeignKey(Uczestnik)
    timestamp = models.DateTimeField("Dodano", auto_now_add=True)
    rezerwowany = models.BooleanField(u"Rezerwowany", default=False)

    class Meta:
        verbose_name = u"Zapis do Frakcji"
        verbose_name_plural = u"Zapisy do Frakcji"

    def __unicode__(self):
        return unicode(self.uczestnik)+" @ "+unicode(self.frakcja)

class Wpis(models.Model):
    """ Pojedynczy wpis w dyskusji pomiędzy członkami danej frakcji """
    fu = models.ForeignKey(FrakcjaUczestnik) # musi być uczestnikiem frakcji
    text = models.TextField(u"Wiadomość")
    timestamp = models.DateTimeField(u"Dodano", auto_now_add = True)

    class Meta:
        verbose_name = u"Wpis w dyskusji frakcji"
        verbose_name_plural = u"Wpisy w dyskusji frakcji"
        ordering = ['timestamp']

apps/zapisy/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm,ValidationError
from django import forms
from models import *

class UczestnictwoForm(ModelForm):
    #plemie = forms.ModelChoiceField(queryset=Plemie.objects.filter(can_register=True))
    larp_uczestnictwo = forms.ChoiceField(widget=forms.Select, choices = (('tak', 'Tak'), ('nie', 'Nie')))
    larp_postac = forms.ChoiceField(widget=forms.Select, choices = (('zadna', u'Wybierz'), ('gotowa', u'Wybiorę gotową postać'), ('wlasna',u'Chcę stworzyć własną postać')))

    def clean_od(self):
        od = self.cleaned_data['od']
        if od is not None:
            if od < self.instance.zlot.start:
                raise ValidationError(u'Nie możesz podać daty przed %s' % str(self.instance.zlot.start))
            if od > self.instance.zlot.koniec:
                raise ValidationError(u'Nie możesz podać daty po %s' % str(self.instance.zlot.koniec))
        return od
    
    def clean_do(self):
        do = self.cleaned_data['do']
        if do is not None:
            if do < self.instance.zlot.start:
                raise ValidationError(u'Nie możesz podać daty przed %s' % str(self.instance.zlot.start))
            if do > self.instance.zlot.koniec:
                raise ValidationError(u'Nie możesz podać daty po %s' % str(self.instance.zlot.koniec))
        return do

    def clean_caly(self):
        caly = self.cleaned_data.get('caly', None)
        do = self.cleaned_data.get('do', None)
        od = self.cleaned_data.get('od', None)
        if not caly and not od and not do:
            raise ValidationError(u'Musisz wybrać jedną z opcji')
        return caly
    
    def clean(self):
        cleaned = self.cleaned_data
        caly = cleaned.get('caly')
        od = cleaned.get('od')
        do = cleaned.get('do')
        if od is not None and do is not None and caly is not None:
            if od == self.instance.zlot.start and do == self.instance.zlot.koniec and caly == 0:
                   self.cleaned_data['caly'] = 1;
        return cleaned
    
    class Meta:
        model = Uczestnictwo
        fields = ('caly','od','do', 'larp_uczestnictwo', 'larp_postac')


class NoweUczestnictwoForm(UczestnictwoForm):
    username = forms.CharField(required = True)
    password = forms.CharField(widget = forms.PasswordInput(), required = True)
    password2 = forms.CharField(widget = forms.PasswordInput(), required = True)
    email = forms.EmailField(required = True)
    larp_uczestnictwo = forms.ChoiceField(widget=forms.Select, choices = (('tak', 'Tak'), ('nie', 'Nie')))
    larp_postac = forms.ChoiceField(widget=forms.Select, choices = (('zadna', u'Wybierz'), ('gotowa', u'Wybiorę gotową postać'), ('wlasna',u'Chcę stworzyć własną postać')))
    
    def clean_email(self):
        try:
            Uczestnik.objects.get(email = self.cleaned_data['email'])
            raise ValidationError(u"Uczestnik o tym adresie email już istnieje")
        except Uczestnik.DoesNotExist:
            return self.cleaned_data['email']
    
    def clean_username(self):
        try:
            Uczestnik.objects.get(username = self.cleaned_data['username'])
            raise ValidationError(u"Uczestnik o tym nicku już istnieje")
        except Uczestnik.DoesNotExist:
            return self.cleaned_data['username']
    
    def clean_password2(self):
        p = p2 = ''
        p = self.cleaned_data.get('password', None)
        p2 = self.cleaned_data.get('password2', None)
        if p != p2:
            raise ValidationError(u'Oba hasła muszą być takie same')
        return self.cleaned_data['password2']
    
    
    class Meta:
        model = Uczestnictwo
        fields = ('username', 'password', 'password2', 'email', 'caly', 'od', 'do', 'larp_uczestnictwo', 'larp_postac')

class LoginForm(forms.Form):
    username = forms.CharField(label=u"Nick", required=True)
    password = forms.CharField(label=u"Hasło", widget=forms.PasswordInput(),required=True)
    
    def clean_username(self):
        try:
            Uczestnik.objects.get(username=self.cleaned_data['username'])
        except Uczestnik.DoesNotExist:
            raise ValidationError(u"Nie ma takiego użytkownika")
        return self.cleaned_data['username']
    
    def clean_password(self):
        try:
            u = Uczestnik.objects.get(username=self.cleaned_data['username'])
            if not u.check_password(self.cleaned_data['password']):
                raise ValidationError(u"Niepoprawne hasło")
        except Uczestnik.DoesNotExist:
            pass
        return self.cleaned_data['password']

class ResetPasswordForm(forms.Form):
    new_password = forms.CharField(label=u"Nowe hasło", widget=forms.PasswordInput(),required=True)
    password_confirm = forms.CharField(label=u"Potwierdź nowe hasło", widget=forms.PasswordInput(),required=True)
    
    def clean(self):
        if self.cleaned_data['new_password'] == self.cleaned_data['password_confirm']:
            return self.cleaned_data
        raise ValidationError(u"Hasła nie są takie same")
        
class ChangePasswordForm(forms.ModelForm):
    old_password = forms.CharField(label=u"Stare hasło", widget=forms.PasswordInput(),required=True)
    new_password = forms.CharField(label=u"Nowe hasło", widget=forms.PasswordInput(),required=True)
    password_confirm = forms.CharField(label=u"Potwierdź nowe hasło", widget=forms.PasswordInput(),required=True)
    
    def clean(self):
        cleaned_data = super(ChangePasswordForm, self).clean()
        if cleaned_data['new_password'] == cleaned_data['password_confirm']:
            if self.instance.check_password(cleaned_data['old_password']): 
                return cleaned_data
            raise ValidationError(u"Stare hasło jest niepoprawne")
        raise ValidationError(u"Nowe hasła nie są takie same")
    
    class Meta:
        model = Uczestnik
        fields = ['old_password', 'new_password', 'password_confirm']

class AddWpisForm(forms.ModelForm):
    class Meta:
        model = Wpis
        fields = ['text',]

apps/news/views.py
# -*- coding: utf-8 -*-
from django.views.generic import TemplateView

from news.models import *
from django.views.generic.list import ListView
from django.shortcuts import get_object_or_404

class EntryView(TemplateView):
    template_name = 'news/single.html'

    def get_context_data(self, **kwargs):
        context = super(EntryView, self).get_context_data(**kwargs)
        context['news'] = get_object_or_404(News, slug=kwargs.get('slug'), )
        return context

class IndexView(ListView):
    template_name = 'news/index.html'
    queryset = News.objects.all().order_by('-id')[:3]

class ArchiveView(ListView):
    template_name = 'news/list.html'
    model = News
    paginate_by = 5

arda/templates/zapisy/dyskusja.html
{% extends "base.html" %}

{% block title %}Dyskusja dla frakcji {{fu.frakcja}}{% endblock %}

{% block main %}
<article class="col col-b-1">
	<div class="col-inner">
	  {% with fu.frakcja as frakcja %}
      <h1 id="{{frakcja.slug}}">{{ frakcja.nazwa }}</h1>
       {% if frakcja.image %}
        <div class="news-image">
          <img src="http://arda.org.pl{{ frakcja.image.url }}" alt="Obraz dla frakcji"/>
        </div>
       {% endif %}
      <h2>Opis frakcji</h2>
      {{ frakcja.opis|safe }}
      <h2>Wprowadzenie fabularne</h2>
      {{ frakcja.wprowadzenie|safe }}
      <h2>Pełny skład frakcji</h2>
      <ul>
      {% for uczestnik in frakcja.frakcjauczestnik_set.all %}
        <li>{{ uczestnik.uczestnik }}</li>
      {% endfor %}
      </ul>
      {% endwith %}
	</div>
</article>
<aside class="col col-b-2">
    <div class="col-inner">
     <h2>Dyskusja dla członków</h2>

    {% if lista_wpisow %}
      {% for wpis in lista_wpisow %}
        <p><strong>{{ wpis.fu.uczestnik }}</strong>: {{ wpis.text|linebreaks }}<br/><small>Dodano: {{ wpis.timestamp }}</small></p>
      {% endfor %}
    {% else %}
    <p>Aktualnie brak wpisów w dyskusji</p>
    {% endif %}
    
    <h3>Dodaj wpis</h3>
    <form action="" method="post">
      {{ form.as_p }}
      <input type="submit" value="Dodaj wpis" class="btn btn-b"/>
    </form>
    </div>
</aside>
{% endblock %}

arda/templates/zapisy/juz_zapisany.html
{% extends "base.html" %}

{% block title %}Zapisałeś się{% endblock %}

{% block main %}
<div class="col col-b-1">
	<div class="col-inner">
		<h1>Zapisy na {{ zlot }}</h1>
        <p>
            <strong>Zapisałeś się na {{ zlot }} już wcześniej. Jeżeli nie dokonywałeś zapisu, skontaktuj się z nami.</strong>
        </p>
        {% comment %}<ul>
            {% for larp in zlot.larp_set.all %}
            <li>{{larp}}</li>
            {% endfor %}
        </ul>
        {% endcomment %}
        <p>
            Do zobaczenia na zlocie!
        </p>
	</div>
</div>

{% include 'aside.html' %}
{% endblock %}

arda/templates/zapisy/larp.html
{% extends "base.html" %}

{% block title %}{{ larp }}{% endblock %}

{% block meta %}
{% if larp.obraz %}
<meta property="og:image" content="http://arda.org.pl{{ larp.obraz.url }}" />
{% endif %}
<meta property="og:title" content="{{ larp }}" />
<meta property="og:type" content="article" />
<meta property="og:description" content="{{ larp.opis|striptags|truncatewords:'100' }}" />
{% endblock %}

{% block main %}
<div class="col col-b-1">
    <div class="col-inner">
       <h1>{{ larp }}</h1>
       {{ larp.opis|safe }}
    </div>
    {% if larp.frakcja_set.all %}
    <h2>Dostępne frakcje</h2>
    <ul>
    {% for frakcja in larp.frakcja_set.all %}
        <li>{% if frakcja.dostepny_opis %}<a href="{% url frakcja_text larp.slug frakcja.slug %}">{{ frakcja }}</a>{% else %}{{ frakcja }}{% endif %}</li>
    {% endfor %}
    </ul>
    {% endif %}
    <div class="fb-like" data-send="false" data-show-faces="true"></div>
</div>
{% include 'aside.html' %}
{% endblock %}

arda/templates/zapisy/password_reset_confirm.html
{% extends "base.html" %}

{% block title %}Resetowanie Hasła{% endblock %}

{% block main %}
<div class="col col-b-1">
    <div class="col-inner">
        {% if msg %}
            {{ msg }}
        {% else %}
    	<h1>Resetowanie hasła</h1>
    	<form action="" method="post" class="centered">
            <p><label for="id_email">Podaj adres email z rejestracji: </label><input id="email" name="email" type="text"/></p>
	        <p class="center"><input type="submit" value="Resetuj hasło"/></p>
    	</form>
        {% endif %}
    </div>
</div>
{% include 'aside.html' %}
{% endblock %}

arda/templates/zapisy/zapis.html
{% extends "base.html" %}

{% block title %}Zapisz się na zlot{% endblock %}

{% block main %}
<div class="col col-b-1">
	<div class="col-inner">
		<h1>Zapisy na Zlot Arda {{ zlot.rok }}</h1>
		{% if zlot.zapisy_otwarte %}
	    <h2>Dla dotychczasowych uczestników</h2>
	    <img src="/site_media/images/pen.jpg" alt="" class="right bordered"/>
	    <p>
	        Jeżeli byłeś na poprzednim Zlocie Arda, posiadasz już konto na stronie. Aby zapisać się na Zlot, przejdź do <a href="{% url 'zapisy_zalogowany' zlot.rok %}">strony zapisów dla dotychczasowych uczestników</a> aby bardzo szybko dołączyć do grona uczestników tegorocznego spotkania.
	    </p>
	    
	    <h2>Nowy uczestnik</h2>
	    <p>
	        Jeżeli nie byłeś na Zlocie Arda, lub rejestrowałeś się w ubiegłym roku przy akredytacji, zapisz się na Zlot. Równocześnie utworzone zostanie twoje indywidualne konto w serwisie.
	    </p>
		<p>
		    Wypełnij poniższy formularz, aby zapisać się na Zlot Arda. <strong>Wszystkie pola są wymagane, chyba że zaznaczono inaczej.</strong>
		</p>
		<form action="" method="post">
		
		<table id="zapisy"> 
			<tr><th><label for="id_username">Nick:</label></th><td>{{ formularz.username }}
				{% if formularz.username.errors %}<br/><span class="error">{% for e in formularz.username.errors %}{{ e }}{% if not forloop.last %},{% endif %}{% endfor %}</span>{% endif %}
			</td></tr> 
			<tr><th><label for="id_password">Hasło:</label></th><td>{{ formularz.password }}
				{% if formularz.password.errors %}<br/><span class="error">{% for e in formularz.password.errors %}{{ e }}{% if not forloop.last %},{% endif %}{% endfor %}</span>{% endif %}
			</td></tr> 
			<tr><th><label for="id_password2">Potwierdź hasło:</label></th><td>{{ formularz.password2 }}
				{% if formularz.password2.errors %}<br/><span class="error">{% for e in formularz.password2.errors %}{{ e }}{% if not forloop.last %},{% endif %}{% endfor %}</span>{% endif %}
			</td></tr> 
			<tr><th><label for="id_email">Adres e-mail:</label></th><td>{{ formularz.email }}
				{% if formularz.email.errors %}<br/><span class="error">{% for e in formularz.email.errors %}{{ e }}{% if not forloop.last %},{% endif %}{% endfor %}</span>{% endif %}
			</td></tr> 
			<tr><th><label for="id_caly">Na cały zlot:</label></th><td>{{ formularz.caly }} 
				{% if formularz.caly.errors %}<br/><span class="error">{% for e in formularz.caly.errors %}{{ e }}{% if not forloop.last %},{% endif %}{% endfor %}</span>{% endif %}
			</td></tr> 
			<tr><th><label for="id_od">Od:</label></th><td>
				<input type="text" name="od" id="id_od" placeholder="{{ zlot.start|date:"Y-m-d" }}">
				<br />Jeżeli jedziesz na część zlotu, podaj od kiedy będziesz (RRRR-MM-DD)<br/>W przeciwnym razie pozostaw puste.
				{% if formularz.od.errors %}<br/><span class="error">{% for e in formularz.od.errors %}{{ e }}{% if not forloop.last %},{% endif %}{% endfor %}</span>{% endif %}
			</td></tr> 
			<tr><th><label for="id_do">Do:</label></th><td>
				<input type="text" name="od" id="id_do" placeholder="{{ zlot.koniec|date:"Y-m-d" }}">
				<br />Jeżeli jedziesz na część zlotu, podaj do kiedy będziesz (RRRR-MM-DD)<br/>W przeciwnym razie pozostaw puste.
				{% if formularz.do.errors %}<br/><span class="error">{% for e in formularz.do.errors %}{{ e }}{% if not forloop.last %},{% endif %}{% endfor %}</span>{% endif %}
			</td></tr> 
			<tr><th><label for="id_caly">Chcę wziąć udział w LARP-ie:</label></th><td>{{ formularz.larp_uczestnictwo }}
				{% if formularz.larp_uczestnictwo.errors %}<br/><span class="error">{% for e in formularz.larp_uczestnictwo.errors %}{{ e }}{% if not forloop.last %},{% endif %}{% endfor %}</span>{% endif %}
			</td></tr> 
			<tr><th><label for="id_caly">Jaka postać cię interesuje:</label></th><td>{{ formularz.larp_postac }}
				{% if formularz.larp_postac.errors %}<br/><span class="error">{% for e in formularz.larp_postac.errors %}{{ e }}{% if not forloop.last %},{% endif %}{% endfor %}</span>{% endif %}
			</td></tr> 
		</table> 
		
		<p class="alt">Rejestrując się wyrażam zgodę na przetwarzanie moich danych osobowych dla potrzeb zwiazanych z organizacją Zlotu Arda oraz informowania o aktualnych wydarzeniach związanych ze Zlotem Arda przez <a href="/zlot/o-nas/">Organizatorów Zlotu Arda</a> {zgodnie z ustawą z dnia 29.08.1997 o Ochronie Danych Osobowych Dz.Ust.nr 133 poz 883}.</p>
		        <p class="center"><input type="submit" value="Zapisz się"/></p>
		
		</form>
		{% else %}
		<p>
			Zapisy w tym roku zostały już zamknięte. Nie jest jednak za późno. Wciąż możesz wydrukować, wypełnić formularz rejestracyjny i przyjechać z nim na {{ zlot }}. 
		</p>
		<p>
			Pamiętaj jednak, by wcześniej skontaktować się z Przewodnikiem Plemienia, do którego chcesz dołączyć i upewnić się, że dostaniesz zgodę na grę w tym plemieniu. 
		</p>
		<p>
			Do zobaczenia na miejscu!
		</p>
		{% endif %}
	</div>
</div>
{% include 'aside.html' %}
{% endblock %}

arda/templates/zapisy/zapis_again.html
{% extends "base.html" %}

{% block title %}Zapisz się na zlot{% endblock %}

{% block main %}
<div class="col col-b-1">
	<div class="col-inner">
		<h1>Zapisy na {{ zlot }}</h1>
		<p>
		    Wypełnij poniższy formularz, aby zapisać się na {{ zlot }}. <strong>Wszystkie pola są wymagane, chyba że zaznaczono inaczej.</strong></p>
		</p>
		<form action="" method="post">
		
		<table class="zapisy"> 
			<tr><th><label for="id_caly">Na cały zlot:</label></th><td>{{ formularz.caly }} 
				{% if formularz.caly.errors %}<br/><span class="error">{% for e in formularz.caly.errors %}{{ e }}{% if not forloop.last %},{% endif %}{% endfor %}</span>{% endif %}
			</td></tr> 
			<tr><th><label for="id_od">Od:</label></th><td>
				<input type="text" name="od" id="id_od" placeholder="{{ zlot.start|date:"Y-m-d" }}">
				<br />Jeżeli jedziesz na część zlotu, podaj od kiedy będziesz (RRRR-MM-DD)<br/>W przeciwnym razie pozostaw puste.
				{% if formularz.od.errors %}<br/><span class="error">{% for e in formularz.od.errors %}{{ e }}{% if not forloop.last %},{% endif %}{% endfor %}</span>{% endif %}
			</td></tr> 
			<tr><th><label for="id_do">Do:</label></th><td>
				<input type="text" name="od" id="id_do" placeholder="{{ zlot.koniec|date:"Y-m-d" }}">
				<br />Jeżeli jedziesz na część zlotu, podaj do kiedy będziesz (RRRR-MM-DD)<br/>W przeciwnym razie pozostaw puste.
				{% if formularz.do.errors %}<br/><span class="error">{% for e in formularz.do.errors %}{{ e }}{% if not forloop.last %},{% endif %}{% endfor %}</span>{% endif %}
			</td></tr> 
			<tr><th><label for="id_caly">Chcę wziąć udział w LARP-ie:</label></th><td>{{ formularz.larp_uczestnictwo }}
				{% if formularz.larp_uczestnictwo.errors %}<br/><span class="error">{% for e in formularz.larp_uczestnictwo.errors %}{{ e }}{% if not forloop.last %},{% endif %}{% endfor %}</span>{% endif %}
			</td></tr> 
			<tr><th><label for="id_caly">Jaka postać cię interesuje:</label></th><td>{{ formularz.larp_postac }}
				{% if formularz.larp_postac.errors %}<br/><span class="error">{% for e in formularz.larp_postac.errors %}{{ e }}{% if not forloop.last %},{% endif %}{% endfor %}</span>{% endif %}
			</td></tr> 
		</table> 
		<p class="alt">Rejestrując się wyrażam zgodę na przetwarzanie moich danych osobowych dla potrzeb zwiazanych z organizacją Zlotu Arda oraz informowania o aktualnych wydarzeniach związanych ze Zlotem Arda przez <a href="/zlot/o-nas/">Organizatorów Zlotu Arda</a> {zgodnie z ustawą z dnia 29.08.1997 o Ochronie Danych Osobowych Dz.Ust.nr 133 poz 883}.</p>
		        <p class="center"><input type="submit" value="Zapisz się"/></p>
		
		</form>
	</div>
</div>
{% include 'aside.html' %}
{% endblock %}

arda/templates/zapisy/zapis_do_frakcji_done.html
{% extends "base.html" %}

{% block title %}{{ frakcja.nazwa }} - Zapis do frakcji skończony{% endblock %}

{% block main %}
<div class="col col-b-1">
    <div class="col-inner">
       <h1>Zapis do frakcji: {{ frakcja.nazwa }}</h1>
       <p><strong>Gratulujemy!</strong> Właśnie zapisałeś się do tej frakcji. Możesz teraz zobaczyć podsumowanie dla swojej frakcji na stronie <a href="{% url frakcja_list %}#{{ frakcja.slug }}">Twoje frakcje</a>. </p>
    </div>
</div>
{% include 'aside.html' %}
{% endblock %}

arda/templates/zapisy/zloty.html
{% extends "base.html" %}

{% block title %}Lista Zlotów Arda{% endblock %}

{% block right_menu %}
  {% include 'zlot/right_menu.html' %}
{% endblock %}

{% block content %}
<div class="span-14 prepend-top append-bottom prepend-1" id="content">
	<h1>Zloty Arda</h1>
</div>
{% endblock %}